# Docs for Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - crewing-data-ext

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python version
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies in a virtual environment
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Zip only the necessary application files
      - name: Zip Artifact for Deployment
        run: |
          zip -r release.zip . \
            -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      # Upload artifact for deployment
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Download artifact created in the build job
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact
      - name: Unzip Artifact
        run: unzip release.zip

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'crewing-data-ext' # Replace with your app name if incorrect
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'production'
